jsonb.formatting=false
%dev.jsonb.formatting=true

mp.jwt.verify.publickey.location=/publicKey.pem
mp.jwt.verify.issuer=https://authbook.dev

# Permit access to the raw OpenAPI YAML/JSON
security.jersey.resource-config.1.path=/openapi
security.jersey.resource-config.1.permit-all=true
