package com.app.book.resource;

import org.apache.commons.lang3.StringUtils;
import org.eclipse.microprofile.auth.LoginConfig;
import org.eclipse.microprofile.openapi.annotations.Operation;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponses;
import org.eclipse.microprofile.openapi.annotations.media.Content;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

import com.app.book.dto.Book;
import com.app.book.mapper.BookMapper;
import com.app.book.model.BookEntity;
import com.app.book.repository.BookRepository;

import io.helidon.security.abac.role.RoleValidator.PermitAll;
import jakarta.annotation.security.DeclareRoles;
import jakarta.annotation.security.RolesAllowed;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.transaction.Transactional;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import lombok.extern.slf4j.Slf4j;

@ApplicationScoped
@Path("/books")
@LoginConfig(authMethod = "MP-JWT")
@DeclareRoles({"admin", "user"})
@Slf4j
public class BookResource {

    private final BookRepository repository;
    private final BookMapper mapper;

    @Inject
    public BookResource(BookRepository repository, BookMapper mapper) {
        this.repository = repository;
        this.mapper = mapper;
    }

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @PermitAll
    @Operation(
        summary = "Search books by criteria",
        description = "Filters the library collection based on title and author strings."
    )
    @APIResponses(value = {
        @APIResponse(
            responseCode = "200",
            description = "Books found successfully",
    		content = @Content(
				mediaType = "application/json",
		        schema = @Schema(implementation = Book.class)
		    )
        ),
        @APIResponse(
            responseCode = "404",
            description = "No books match the criteria"
        ),
        @APIResponse(
            responseCode = "500",
            description = "Internal server error"
        )
    })
    public Response searchBooks(@QueryParam("title") String title, @QueryParam("author") String author) {
    	var bookEntities = repository.findByTitleAndAuthor(title, author);
    	var books = bookEntities.stream().map(mapper::toDto).toList();
    	log.info("Fetched {} books for search criteria.", books.size());
    	return Response.ok(books).build();
    }
    
    @GET
    @Path("/{id}")
    @Produces(MediaType.APPLICATION_JSON)
    @PermitAll
    @Operation(
        summary = "Get book by ID",
        description = "Retrieves a single book record from the library database using its unique identifier."
    )
    @APIResponses(value = {
        @APIResponse(
            responseCode = "200",
            description = "Book found",
            content = @Content(
                mediaType = "application/json",
                schema = @Schema(implementation = Book.class)
            )
        ),
        @APIResponse(
            responseCode = "404",
            description = "Book with the given ID does not exist"
        )
    })
    public Response getById(@PathParam("id") long id) {
    	return repository.findById(id)
                .map(mapper::toDto)
                .map(book -> {
                		log.info("The book with id '{}' fetched.", id);
                    return Response.ok(book).build();
                })
                .orElseGet(() -> Response.status(Response.Status.NOT_FOUND)
                        .entity(bookNotFound(id)).build()
                );
    }

    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @RolesAllowed({"admin"})
    @Transactional
    @Operation(
        summary = "Create a new book",
        description = "Adds a new book to the library. The ID is automatically generated by the system."
    )
    @APIResponses(value = {
        @APIResponse(
            responseCode = "201",
            description = "Book created successfully",
            content = @Content(
                mediaType = "application/json",
                schema = @Schema(implementation = Book.class)
            )
        ),
        @APIResponse(
            responseCode = "400",
            description = "Invalid input data"
        )
    })
    public Response create(Book book) {
    	if (StringUtils.isBlank(book.getTitle())) {
            return Response.status(Response.Status.BAD_REQUEST).entity(invalidBook()).build();
        }
    	var bookEntity = mapper.toEntity(book);
        var savedBookEntity = repository.insert(bookEntity);
        var savedBook = mapper.toDto(savedBookEntity);
        log.info("The book '{}' saved.", savedBook.getTitle());
        return Response.status(Response.Status.CREATED).entity(savedBook).build();
    }

    @PUT
    @Path("/{id}")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @RolesAllowed({"admin"})
    @Transactional
    @Operation(
        summary = "Update an existing book",
        description = "Updates the title and author of a book identified by the ID in the URL path."
    )
    @APIResponses(value = {
        @APIResponse(
            responseCode = "200",
            description = "Book updated successfully",
            content = @Content(
                mediaType = "application/json",
                schema = @Schema(implementation = Book.class)
            )
        ),
        @APIResponse(
            responseCode = "404",
            description = "Book not found"
        ),
        @APIResponse(
            responseCode = "400",
            description = "Invalid request data"
        )
    })
    public Response update(@PathParam("id") long id, Book book) {
    	if (StringUtils.isBlank(book.getTitle())) {
            return Response.status(Response.Status.BAD_REQUEST).entity(invalidBook()).build();
        }
        return repository.findById(id)
            .map(_ -> {
            		var updatedBookEntity = BookEntity.builder().id(id).title(book.getTitle()).author(book.getAuthor()).build();
            		repository.merge(updatedBookEntity);
            		var updatedBook = mapper.toDto(updatedBookEntity);
                log.info("The book '{}' updated.", updatedBook.getTitle());
                return Response.ok(updatedBook).build();
            })
            .orElseGet(() -> Response.status(Response.Status.NOT_FOUND)
                    .entity(bookNotFound(id)).build()
            );
    }

    @DELETE
    @Path("/{id}")
    @Produces(MediaType.APPLICATION_JSON)
    @RolesAllowed({"admin"})
    @Transactional
    @Operation(
        summary = "Delete a book",
        description = "Permanently removes a book from the library database by its ID."
    )
    @APIResponses(value = {
        @APIResponse(
            responseCode = "204",
            description = "Book successfully deleted"
        ),
        @APIResponse(
            responseCode = "404",
            description = "Book not found, nothing was deleted"
        ),
        @APIResponse(
            responseCode = "500",
            description = "Internal server error during deletion"
        )
    })
    public Response delete(@PathParam("id") long id) {
        return repository.findById(id)
            .map(book -> {
                repository.delete(book);
                log.info("The book '{}' deleted.", book.getTitle());
                return Response.noContent().build();
            })
            .orElseGet(() -> Response.status(Response.Status.NOT_FOUND)
                    .entity(bookNotFound(id)).build()
            );
    }

    private String invalidBook() {
        log.error("Title must not be empty");
        return """
                {
                    "error": "Title must not be empty"
                }
                """;
    }
    
    private String bookNotFound(long id) {
        log.error("The book with id '{}' not found.", id);
        return """
                {
                    "error": "The book with id '%d' not found"
                }
                """.formatted(id);
    }
}
